baseURL = "https://joelheaps.com/"
languageCode = "en-US"
title = "Joel's Blog ğŸ“"

enableRobotsTXT = true

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[permalinks]
  post = "/:year/:month/:day/:slug"

## Main Menu English
[[menu.main]]
  name = "Local Hiking"
  weight = 100
  url = "/local-hiking"
